name: sliver_dashboard
description: "Smooth, sliver-based drag & resize grid engine. Supports nested grids, cross-sliver DND, responsive layouts. Native Flutter alternative to GridStack & react-grid-layout."
homepage: https://github.com/scalz/sliver_dashboard
repository: https://github.com/scalz/sliver_dashboard
issue_tracker: https://github.com/scalz/sliver_dashboard/issues
version: 2.1.1

environment:
  sdk:  ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.18.0
  state_beacon: ^3.1.1

dev_dependencies:
  coverage: ^1.15.1

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

topics:
  - dashboard
  - grid
  - layout
  - draggable
  - resizable